# Generated by Django 4.0.4 on 2022-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='appropriate_for',
            field=models.CharField(choices=[('Under 8', 'Under 8'), ('8 - 15', '8 - 15'), ('Adults', 'Adults')], max_length=20),
        ),
    ]
